Repository scseong/til-motivation-project, pull requests merged in 2023-12, with the labels that each got.

#6 config: 프론트엔드 프로젝트 추가 설정
  next.config.js
  package.json
  src/app/(afterLogin)/layout.tsx
  src/app/(afterLogin)/posts/create/page.tsx
  src/app/(afterLogin)/posts/update/page.tsx
  src/app/(afterLogin)/profile/update/page.tsx
  src/app/(beforeLogin)/auth/login/page.tsx
  src/app/(beforeLogin)/auth/signup/page.tsx
  src/app/(beforeLogin)/home/page.module.scss
  src/app/(beforeLogin)/home/page.tsx
  src/app/(beforeLogin)/layout.tsx
  src/app/(beforeLogin)/posts/[id]/page.tsx
  src/app/(beforeLogin)/profile/[username]/page.tsx
  src/app/(beforeLogin)/search/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/app/posts/create/post.tsx
  src/app/variables.css
  src/typing/Post.ts
  src/typing/Profile.ts
  src/typing/User.ts
  src/typing/props.ts
  yarn.lock
Labels: 기능, 설정

#9 feat: 로그인 폼 UI 구현
  src/app/(beforeLogin)/auth/login/login.module.scss
  src/app/(beforeLogin)/auth/login/page.tsx
  src/app/globals.css
  src/app/variables.css
  src/shared/auth.ts
  src/shared/firebase.ts
Labels: 기능, UI

#10 feat: 회원가입 폼 UI
  src/app/(beforeLogin)/auth/signup/page.tsx
  src/app/(beforeLogin)/auth/signup/signup.module.scss
  src/app/variables.css
Labels: UI

#12 style: 디테일 페이지 화면 구성
  .gitignore
  src/app/(beforeLogin)/posts/[id]/_components/AddComment.module.scss
  src/app/(beforeLogin)/posts/[id]/_components/AddComment.tsx
  src/app/(beforeLogin)/posts/[id]/_components/CommentList.module.scss
  src/app/(beforeLogin)/posts/[id]/_components/CommnetList.tsx
  src/app/(beforeLogin)/posts/[id]/_components/Post.module.scss
  src/app/(beforeLogin)/posts/[id]/_components/Post.tsx
  src/app/(beforeLogin)/posts/[id]/page.tsx
  src/app/globals.css
  src/app/variables.css
Labels: UI

#14 [style/homeUi] Home UI
  public/images/logo.png
  src/app/(beforeLogin)/_components/Footer.tsx
  src/app/(beforeLogin)/_components/NavBar.tsx
  src/app/(beforeLogin)/_components/footer.module.scss
  src/app/(beforeLogin)/_components/navbar.module.scss
  src/app/(beforeLogin)/home/_components/List.tsx
  src/app/(beforeLogin)/home/_components/SideBar.tsx
  src/app/(beforeLogin)/home/_components/WriteBar.tsx
  src/app/(beforeLogin)/home/_components/list.module.scss
  src/app/(beforeLogin)/home/_components/sidebar.module.scss
  src/app/(beforeLogin)/home/_components/writebar.module.scss
  src/app/(beforeLogin)/home/page.module.scss
  src/app/(beforeLogin)/home/page.tsx
  src/app/(beforeLogin)/layout.tsx
  src/app/(beforeLogin)/search/page.tsx
Labels: UI

#18 feat: search 모달 및 반응형 구현
  package.json
  src/app/(beforeLogin)/_components/Modal.tsx
  src/app/(beforeLogin)/_components/NavBar.tsx
  src/app/(beforeLogin)/_components/modal.module.scss
  src/app/(beforeLogin)/_components/navbar.module.scss
  src/app/(beforeLogin)/home/page.tsx
  yarn.lock
Labels: 기능, UI

#20 fix: layout 수정
  src/app/(beforeLogin)/layout.tsx
  src/app/_components/Footer.tsx
  src/app/_components/Modal.tsx
  src/app/_components/NavBar.tsx
  src/app/_components/footer.module.scss
  src/app/_components/modal.module.scss
  src/app/_components/navbar.module.scss
  src/app/layout.tsx
Labels: 수정

#25 파이어베이스연결
  package.json
  src/api/posts.ts
  src/app/(beforeLogin)/auth/login/page.tsx
  src/app/(beforeLogin)/auth/signup/page.tsx
  src/app/(beforeLogin)/home/_components/List.tsx
  src/app/(beforeLogin)/home/_components/list.module.scss
  src/app/(beforeLogin)/layout.tsx
  src/app/(beforeLogin)/search/page.module.scss
  src/app/(beforeLogin)/search/page.tsx
  src/app/_components/Loader.tsx
  src/app/_components/Modal.tsx
  src/app/_components/loader.module.scss
  src/app/layout.tsx
  src/typing/Post.ts
  src/typing/Profile.ts
  src/utils/ReactQueryProviders.tsx
  src/utils/regex.ts
  yarn.lock
Labels: 기능

#26 feat/댓글 추가하기
  package.json
  src/app/(beforeLogin)/posts/[id]/_components/AddComment.module.scss
  src/app/(beforeLogin)/posts/[id]/_components/AddComment.tsx
  src/app/(beforeLogin)/posts/[id]/_components/CommentList.tsx
  src/app/(beforeLogin)/posts/[id]/_components/CommnetList.tsx
  src/app/(beforeLogin)/posts/[id]/page.module.css
  src/app/(beforeLogin)/posts/[id]/page.tsx
  src/shared/comment.ts
  src/typing/Comment.ts
  src/typing/Post.ts
  src/utils/ReactQueryProviders.tsx
  yarn.lock
Labels: 버그, 기능

#27 Feat/ 포스팅 페이지 개발
  package.json
  src/api/posts.ts
  src/app/(afterLogin)/posts/create/_components/Button.tsx
  src/app/(afterLogin)/posts/create/_components/ClientOpenGraph.tsx
  src/app/(afterLogin)/posts/create/_components/Editor.tsx
  src/app/(afterLogin)/posts/create/_components/LinkPreviewCard.tsx
  src/app/(afterLogin)/posts/create/_components/Tag.tsx
  src/app/(afterLogin)/posts/create/_components/button.module.scss
  src/app/(afterLogin)/posts/create/_components/clientOpenGraph.module.scss
  src/app/(afterLogin)/posts/create/_components/linkPreviewCard.module.scss
  src/app/(afterLogin)/posts/create/_components/serverOpenGraph.ts
  src/app/(afterLogin)/posts/create/_components/tag.module.scss
  src/app/(afterLogin)/posts/create/page.tsx
  src/app/(afterLogin)/posts/create/postCreatePage.module.scss
  src/app/(beforeLogin)/home/_components/List.tsx
  src/typing/Post.ts
  yarn.lock
Labels: 기능, UI

#30 fix: 컬렉션 오류 수정
  src/api/posts.ts
  src/app/(afterLogin)/posts/create/page.tsx
Labels: 버그

#34 Feat/editor 메인 페이지 editor html 적용
  src/app/(beforeLogin)/home/_components/List.tsx
Labels: 기능, UI

#35 Search 검색 기능 구현
  src/app/(beforeLogin)/home/_components/List.tsx
  src/app/(beforeLogin)/search/page.tsx
  src/app/_components/NavBar.tsx
Labels: 기능

#38 feat: 회원가입 기능 구현
  package.json
  src/app/(beforeLogin)/auth/signup/page.tsx
  src/app/(beforeLogin)/auth/signup/signup.module.scss
  src/app/layout.tsx
  src/shared/auth.ts
  src/shared/error.ts
  yarn.lock
Labels: 기능, 수정
