Repository scseong/til-motivation-project, pull requests merged in 2024-01, with the labels that each got.

#40 fix: posts 타입 변경 및 적용 (#4)
  src/api/posts.ts
  src/app/(afterLogin)/posts/create/_components/ClientOpenGraph.tsx
  src/app/(afterLogin)/posts/create/_components/LinkPreviewCard.tsx
  src/app/(afterLogin)/posts/create/page.tsx
  src/app/(beforeLogin)/home/_components/List.tsx
  src/typing/Post.ts
Labels: 수정

#41 fix,feture/home 좋아요 구현, 정렬
  src/api/posts.ts
  src/app/(beforeLogin)/home/_components/List.tsx
  src/app/(beforeLogin)/home/_components/list.module.scss
  src/app/(beforeLogin)/search/page.tsx
Labels: 기능, 수정

#43 feat/home DATA
  src/api/posts.ts
  src/app/(afterLogin)/posts/create/page.tsx
  src/app/(beforeLogin)/home/_components/List.tsx
  src/app/(beforeLogin)/home/_components/list.module.scss
  src/typing/Post.ts
Labels: 기능, 수정

#44 style/profile 프로필 수정 페이지 UI
  public/images/profileEdit.png
  src/app/(afterLogin)/posts/create/_components/Tag.tsx
  src/app/(afterLogin)/profile/[username]/_components/Calendar.tsx
  src/app/(afterLogin)/profile/[username]/_components/LikePostList.tsx
  src/app/(afterLogin)/profile/[username]/_components/ModalController .tsx
  src/app/(afterLogin)/profile/[username]/_components/Profile.tsx
  src/app/(afterLogin)/profile/[username]/_components/ProfileTIL.tsx
  src/app/(afterLogin)/profile/[username]/_components/UpdateModal.module.scss
  src/app/(afterLogin)/profile/[username]/_components/UpdateModal.tsx
  src/app/(afterLogin)/profile/[username]/_components/UserProfile.module.scss
  src/app/(afterLogin)/profile/[username]/_components/UserProfile.tsx
  src/app/(afterLogin)/profile/[username]/_components/openProfileEdit.tsx
  src/app/(afterLogin)/profile/[username]/_components/profile.module.scss
  src/app/(afterLogin)/profile/[username]/_components/profileTIL.module.scss
  src/app/(afterLogin)/profile/[username]/layout.tsx
  src/app/(afterLogin)/profile/[username]/page.tsx
  src/app/(afterLogin)/profile/[username]/update/page.tsx
  src/app/(afterLogin)/profile/update/page.tsx
  src/app/(beforeLogin)/profile/[username]/page.tsx
  src/app/_components/NavBar.tsx
  src/app/_components/Spacer.tsx
Labels: UI

#46 [home/clipBoard] clipBoard
  package.json
  src/app/(beforeLogin)/home/_components/List.tsx
  src/app/(beforeLogin)/home/_components/getTimeAgo.ts
  yarn.lock
Labels: 기능

#49 feat: SNS 로그인 후 컬렉션 생성
  src/app/(beforeLogin)/auth/login/login.module.scss
  src/app/(beforeLogin)/auth/login/page.tsx
  src/app/api/auth/login/route.ts
  src/shared/auth.ts
  src/shared/firebase-admin.ts
  src/shared/firebase.ts
  src/typing/Profile.ts
  src/typing/User.ts
Labels: 기능

#52 feat: 라우트 보호
  package.json
  src/app/api/auth/login/route.ts
  src/middleware.ts
  yarn.lock
Labels: 기능

#56 Feat/update comment
  package.json
  src/api/posts.ts
  src/app/(afterLogin)/posts/create/page.tsx
  src/app/(beforeLogin)/home/_components/List.tsx
  src/app/(beforeLogin)/posts/[id]/_components/AddComment.module.scss
  src/app/(beforeLogin)/posts/[id]/_components/AddComment.tsx
  src/app/(beforeLogin)/posts/[id]/_components/CommentList.module.scss
  src/app/(beforeLogin)/posts/[id]/_components/CommentList.tsx
  src/app/(beforeLogin)/posts/[id]/_components/Post.module.scss
  src/app/(beforeLogin)/posts/[id]/_components/Post.tsx
  src/app/(beforeLogin)/posts/[id]/page.tsx
  src/shared/comment.ts
  src/typing/Comment.ts
  src/typing/Post.ts
  yarn.lock
Labels: 버그, 기능

#60 Feat/heatmap 잔디밭 구조설계
  package.json
  src/app/(afterLogin)/profile/[username]/_components/Calendar.tsx
  src/app/(afterLogin)/profile/[username]/_components/UserProfile.module.scss
  src/app/(afterLogin)/profile/[username]/_components/UserProfile.tsx
  src/app/(afterLogin)/profile/[username]/_components/converter.ts
  src/app/(afterLogin)/profile/[username]/_components/openProfileEdit.tsx
  src/app/(afterLogin)/profile/[username]/_components/profile.module.scss
  src/app/(beforeLogin)/home/_components/List.tsx
  src/app/_components/Spacer.tsx
  yarn.lock
Labels: 기능, UI

#62 feat: 로그아웃 기능 추가
  src/app/api/auth/login/route.ts
  src/app/api/auth/logout/route.ts
  src/shared/auth.ts
  src/shared/firebase-admin.ts
  src/typing/API.ts
Labels: 기능

#64 feat: firebase user 컨텍스트
  src/app/(beforeLogin)/auth/login/page.tsx
  src/app/_components/AuthSession.tsx
  src/app/layout.tsx
Labels: 기능

#65 feat: 게시글 유저정보 등록
  src/app/(afterLogin)/posts/create/page.tsx
Labels: 기능

#66 Style/post detail
  src/api/posts.ts
  src/app/(beforeLogin)/posts/[id]/_components/CommentList.tsx
  src/app/(beforeLogin)/posts/[id]/_components/Post.module.scss
  src/app/(beforeLogin)/posts/[id]/_components/Post.tsx
Labels: 기능, UI

#68 feat: UserProfile 컨텍스트 관리
  src/app/_components/AuthSession.tsx
  src/shared/auth.ts
Labels: 기능

#69 Style/post detail 게시물 디테일 스타일 수정
  src/app/(beforeLogin)/posts/[id]/_components/Post.module.scss
Labels: UI

#71 [fix/show post detail] 게시물, 댓글 업데이트 오류 수정
  src/app/(beforeLogin)/posts/[id]/_components/AddComment.tsx
  src/app/(beforeLogin)/posts/[id]/_components/CommentList.tsx
  src/app/(beforeLogin)/posts/[id]/_components/Post.tsx
Labels: 버그

#73 feat/after home 로그인 후 UX
  src/api/posts.ts
  src/api/users.ts
  src/app/(beforeLogin)/home/_components/List.tsx
  src/app/(beforeLogin)/home/_components/SideBar.tsx
  src/app/(beforeLogin)/home/_components/sidebar.module.scss
  src/app/(beforeLogin)/posts/[id]/_components/Post.module.scss
  src/app/(beforeLogin)/posts/[id]/_components/PostDetail.tsx
  src/app/(beforeLogin)/posts/[id]/page.tsx
  src/app/_components/NavBar.tsx
  src/app/_components/navbar.module.scss
  src/typing/Post.ts
  src/typing/Profile.ts
  src/typing/User.ts
Labels: 기능

#75 Feat/profile 프로필 페이지 완성
  src/api/posts.ts
  src/app/(afterLogin)/posts/create/_components/ClientOpenGraph.tsx
  src/app/(afterLogin)/posts/create/_components/LinkPreviewCard.tsx
  src/app/(afterLogin)/posts/create/_components/Tag.tsx
  src/app/(afterLogin)/posts/create/page.tsx
  src/app/(afterLogin)/profile/[username]/_components/Calendar.tsx
  src/app/(afterLogin)/profile/[username]/_components/LikePostList.tsx
  src/app/(afterLogin)/profile/[username]/_components/PageCompoent.tsx
  src/app/(afterLogin)/profile/[username]/_components/Profile.tsx
  src/app/(afterLogin)/profile/[username]/_components/ProfilePosts.tsx
  src/app/(afterLogin)/profile/[username]/_components/ProfileTIL.tsx
  src/app/(afterLogin)/profile/[username]/_components/UpdateModal.tsx
  src/app/(afterLogin)/profile/[username]/_components/UserProfile.module.scss
  src/app/(afterLogin)/profile/[username]/_components/UserProfile.tsx
  src/app/(afterLogin)/profile/[username]/_components/converter.ts
  src/app/(afterLogin)/profile/[username]/_components/profileTIL.module.scss
  src/app/(afterLogin)/profile/[username]/page.tsx
  src/app/(afterLogin)/profile/[username]/update/page.tsx
  src/app/(beforeLogin)/home/_components/List.tsx
  src/typing/Post.ts
Labels: 기능, UI

#76 feat: 게시물 등록시 +1일
  next.config.js
  src/api/users.ts
  src/app/(afterLogin)/posts/create/page.tsx
  src/app/(beforeLogin)/home/_components/SideBar.tsx
  src/app/(beforeLogin)/home/_components/WriteBar.tsx
  src/app/(beforeLogin)/home/_components/writebar.module.scss
  src/app/_components/navbar.module.scss
  src/shared/auth.ts
  src/typing/Profile.ts
  src/typing/User.ts
Labels: 기능, 수정

#78 feat: 이메일, SNS 로그인 기능 수정
  next.config.js
  package.json
  src/app/(beforeLogin)/auth/login/page.tsx
  src/app/(beforeLogin)/auth/signup/page.tsx
  src/app/_components/AuthSession.tsx
  src/app/_components/NavBar.tsx
  src/app/api/auth/login/route.ts
  src/app/api/auth/logout/route.ts
  src/middleware.ts
  src/shared/auth.ts
  src/shared/firebase-admin.ts
  yarn.lock
Labels: 기능, 리팩토링

#79 [feat/edit post] 게시글 수정 및 삭제하기
  src/api/posts.ts
  src/app/(afterLogin)/posts/create/_components/ClientOpenGraph.tsx
  src/app/(afterLogin)/posts/create/_components/Editor.tsx
  src/app/(afterLogin)/posts/create/_components/Tag.tsx
  src/app/(afterLogin)/posts/update/[id]/page.tsx
  src/app/(afterLogin)/posts/update/[id]/postUpdatePage.module.scss
  src/app/(afterLogin)/posts/update/page.tsx
  src/app/(beforeLogin)/posts/[id]/_components/CommentList.tsx
  src/app/(beforeLogin)/posts/[id]/_components/Post.module.scss
  src/app/(beforeLogin)/posts/[id]/_components/PostDetail.tsx
Labels: 기능, UI

#82 Feat/updateprofile 프로필 수정 기능
  src/api/posts.ts
  src/api/users.ts
  src/app/(afterLogin)/profile/[username]/_components/UpdateModal.tsx
  src/app/(afterLogin)/profile/[username]/_components/UserProfile.tsx
Labels: 기능

#83 Feat/edit post
  next.config.js
  src/app/(beforeLogin)/posts/[id]/_components/AddComment.tsx
  src/app/(beforeLogin)/posts/[id]/_components/CommentList.module.scss
  src/app/(beforeLogin)/posts/[id]/_components/CommentList.tsx
  src/app/(beforeLogin)/posts/[id]/_components/PostDetail.tsx
Labels: 버그, 기능

#85 fix: 배포 시 경로 문제 해결
  src/app/(afterLogin)/posts/create/_components/Button.tsx
  src/app/(afterLogin)/profile/[username]/_components/OpenProfileUpdate.tsx
  src/app/(afterLogin)/profile/[username]/_components/UserProfile.tsx
Labels: 버그

#86 수정
  src/app/(afterLogin)/profile/[username]/_components/UserProfile.tsx
  src/app/(beforeLogin)/search/page.module.scss
  src/app/(beforeLogin)/search/page.tsx
Labels: 기능, UI

#88 배포 후 수정
  src/api/users.ts
  src/app/(afterLogin)/profile/[username]/_components/PageCompoent.tsx
  src/app/(afterLogin)/profile/[username]/_components/UpdateModal.tsx
  src/app/(beforeLogin)/home/_components/SideBar.tsx
  src/app/(beforeLogin)/home/_components/sidebar.module.scss
  src/app/(beforeLogin)/posts/[id]/_components/CommentList.module.scss
  src/app/(beforeLogin)/posts/[id]/_components/CommentList.tsx
Labels: 기능, UI

#89 feat: v1.0.1 오류 수정
  src/app/(beforeLogin)/auth/login/login.module.scss
  src/app/(beforeLogin)/auth/login/page.tsx
  src/app/_components/AuthSession.tsx
  src/app/api/auth/logout/route.ts
  src/shared/error.ts
Labels: 버그, 배포

#90 fix: 메인 컨테이너 최소 높이 변경
  src/app/(afterLogin)/profile/[username]/_components/profile.module.scss
  src/app/(beforeLogin)/auth/login/page.tsx
  src/app/(beforeLogin)/auth/signup/signup.module.scss
  src/app/_components/AuthSession.tsx
  src/app/api/auth/logout/route.ts
Labels: 수정
